### ISSUE TITLE
[1.20.1] Embeddium++ Crash with Zume

### ISSUE THREAD

**Issue by Starexify** [SrRapero720/EmbeddiumAdditions#8]
When I launched latest Embeddium++ version and it installed Zume itself, it crashes.
Log: https://pastebin.com/F2D7XD0x

No idea why. Just remove Zume better. There are better alternatives 👍

**Comment by SrRapero720** [comment]
Crash is not related to embeddium. Is related to essentials.

I will remove zume as required dependency in a few hours, I am busy with other things :P
